### ISSUE TITLE
files from startup screen recent files list are not loaded in 2.8

### ISSUE THREAD

**Issue by trose-neuro** [bonsai-rx/bonsai#1539] opened 2023-08-28 09:50 UTC
When selecting a file from the startup recent files list, files are not loaded in 2.8 anymore. Going via main menu works.

**Comment by glopesdev** [comment] 2023-08-31 08:47
@trose-neuro This is working for me, so I cannot reproduce. Can you elaborate on the error a little bit more? Is there an error, nothing happens when you click, or does bonsai open to a blank canvas?

If the latter, this may be a duplicate of #1538

**Comment by glopesdev** [comment] 2023-08-31 09:15
@trose-neuro I have pinned this down and assuming that this is what you are experiencing. Could happen not just with files having spaces, but also if any of the path folders has spaces, e.g. user name, etc

**Closed** 2023-08-31 09:14 UTC

**Comment by trose-neuro** [comment] 2023-09-11 15:15
@glopesdev sorry for coming back so late.

This may indeed be related / the same issue. But our filenames have no spaces (but underscores). The exact (slightly weird) behavior is the following:

1. Select File 'A' - `DualCamBasler_WEAR_2p_triggered_GPU_update_wearBINARY.bonsai` from startup screen
2. blank canvas
3. opening same file within Bonsai: everything runs fine.

BUT
3. opening a file different from the one selected under 1 (same filename in different folder) leads to a crash:

![image](https://github.com/bonsai-rx/bonsai/assets/4570253/b140c7fe-9a8a-400c-b7cf-698966c65f32)

The same happens when opening workflows straight from explorer.

Not a big issue for us - but noteworthy.
