### ISSUE TITLE
Feature request: Run task/script when shutting down the workflow

### ISSUE THREAD

**Issue by caniko** [bonsai-rx/bonsai#822] opened 2021-09-02 09:51 UTC
We often run Bonsai along with many other external applications. A nice feature would be to initiate a set of scripts when shutting down Bonsai. These scripts would for instance use BonsaiMQ to send a signal to the external applications to state that the shutdown is in progress so that these external workflows can act accordingly.

**Implementation logic**
A node that launches sibling nodes when the workflow is shutting down. These sibling nodes should be nodes that don't have an event loop as they would never shut down in these cases.

**Comment by glopesdev** [comment] 2021-09-02 18:17
Closing as duplicate of #689

**Closed by glopesdev** 2021-09-02 18:17 UTC
Labels: duplicate
