### ISSUE TITLE
managing ROIs that disappear/change over time

### ISSUE THREAD

**Issue by amchagas** [bonsai-rx/bonsai#884] opened 2022-04-25 18:22 UTC
### Discussed in https://github.com/bonsai-rx/bonsai/discussions/883

<div type='discussions-op-text'>

<sup>Originally posted by **amchagas** April 25, 2022</sup>
Hi folks!

I am working on a [project](https://github.com/Sussex-Neuroscience/embryo-monitoring) to monitor drosophila embryo development over long periods of time.

## setup: 
- We have a cheap ELP camera recording a 3D printed plate with 4 wells. 
- Within each well there are 6 embryos in their eggs.
- Using [Bonsai pipeline](https://github.com/Sussex-Neuroscience/embryo-monitoring/tree/main/software/analysis/bonsai) we:
  - take a 4fps video of the plate for ~16 hours
  - create ROIs of each embryo (based on HSV threshold) and track the width, height and average brightness of each embryo.

## problem 1:
Sometimes the ROI indexes change overtime (I think this is due to the fact that they have similar sizes), even though I am not using any type of sort for them. When that happens, my datastreams get mixed and so I would like to avoid this automatic changes in the ROI indexes.

As one solution for this, we improved lighting conditions and everything looks quite stable now. However it would be good to know if there is a way to manually fix ROI indexes/locations in software. The reason being that if other people use this pipeline and are not careful with lighting they are going to get data that is mixed and looks good enough for analysis (the worst kind of data)

## problem2:
The embryos hatch at different times, and when the first one out of the 24 hatches and moves out of its original place, that ROI is "lost" and an exception is thrown since that specific ROI index does not exist anymore. 

## Question:
Is there an easy way to handle this exception? maybe put all the values related to that ROI and index to zeros?

I have addded a sample video to a dropbox folder. This can be accessed [here](https://www.dropbox.com/s/zpi3q9kevb3fmrn/bonsai_example.avi?dl=0)

I hope all of this is clear. Thanks for developing Bonsai and for the support here!!

--- 

## Update 1:

Seems  Problem 1 can be solved by using a conversion to grayscale and then simple thresholding, instead of using HSV thresholding. From what I was able to put together, as the embryos develop and get brighter in their center, the HSV threshold method was giving out dark spots in the middle which was significantly changing the contours detected by "find contours" and therefore giving out ROI changes...

## Update 2:

Seems I was not correct with Update 1. The problem is not as pronounced when I use simple grayscale and thresholding, but it is still there... here is a small gif showing what is going on:
![Bonsai_CaPKwsBUxD](https://user-images.githubusercontent.com/3624486/165150315-62bd7759-feb3-49a8-8679-60e50ce4a457.gif)

**Comment by glopesdev** [comment] 2022-06-03 12:44
Duplicate of #883

**Closed by glopesdev** 2022-06-03 12:44 UTC
