### ISSUE TITLE
Editor crashes on file open when failing to load included workflow

### ISSUE THREAD

**Issue by glopesdev** [bonsai-rx/bonsai#824] opened 2021-09-07 08:21 UTC
To reproduce: open a workflow file containing missing included workflows, or invalid paths to embedded assemblies which cannot load (i.e. an included workflow pointing to a missing package).

This is a regression caused by fixing #800 with eager loading without accounting for potential exceptions raised during load. If this is the case, it might be okay to simply catch any exceptions to ensure `ArgumentRange` never throws, and wait for the error to be thrown during proper workflow building.

**Comment by PathogenDavid** [comment] 2024-07-10 06:43
I noticed while reviewing https://github.com/bonsai-rx/bonsai/pull/1890 that with this fix it's possible that an exception in the wrong place (namely, after `workflow` is initially assigned) could leave `IncludeWorkflowBuilder` in an inconsistent state and the exception would not show up later as intended.

The easiest fix is probably to store the newly-created `workflow` in a local and only assign it to `this.workflow` at the very end of the `if (workflow == null || lastWriteTime > writeTime)` block in `EnsureWorkflow`.

**Closed** 2024-07-10 22:06 UTC
Labels: bug, critical
