### ISSUE TITLE
TableLayoutPanel state not being saved

### ISSUE THREAD

**Issue by jonnew** [bonsai-rx/bonsai#1093] opened 2022-10-19 15:55 UTC
I'm using [TableLayoutPanel](https://github.com/bonsai-rx/bonsai/blob/26f371dda23ff547e8a3ca27b2b14fba32e02e52/Bonsai.Design.Visualizers/TableLayoutPanelVisualizer.cs) to group visualizers. I put all my panes in there while running and format them how I like. I press Ctrl+S or File->Save. I restart the workflow and most of the time I'm presented with a blank grey pane for the TableLayoutPanel Node's Visualizer, with none of my formating saved.  Sometimes, partial state does seem to be saved (e.g. there will be one sub pane still in the window, but with none of its internal settings (History, Channels per page, etc) saved, but I've not been able to detect a pattern to this.

Bonsai Version: 2.7.0

**Comment by glopesdev** [comment] 2022-10-19 21:37
@jonnew this might be a regression, since we did make substantial changes to this for 2.7 for the new features I discuss below. Can you send an example workflow with basic steps to reproduce so I can have a look?

Basically, in 2.7 we introduced a new way of designing composite visualizers explicit in the workflow. The goal was to actually allow us to move away from having to do the design by drag-and-dropping entirely and allow visualizers to be combined directly in code. This is actually the preferred way we will try to push going forward. However, we did want to keep backwards compatible so both approaches should in theory be available.

For reference, below is an example of how you would combine three visualizers and nested compound visualizers in a `TableLayoutPanel`:

<img height="200px" src="https://user-images.githubusercontent.com/5315880/196809027-ce4ca01c-7037-47a4-9378-9c59173ef54c.png"/>

[visualizermapping-example.zip](https://github.com/bonsai-rx/bonsai/files/9824536/visualizermapping-example.zip)

With this approach you can stack any visualizer exactly as you want, and you can even stack recursively within the composite (e.g. you can nest tableLayouts inside tableLayouts). You can also group these inside a group and pipe the final TableLayout to the output and the visualizer of the group will be the visualizer of the compound, which is great for include workflows, etc.

In any case, I think I've seen some weirdness around this myself, so would be great to pin down what exactly is the cause for this.

**Comment by jonnew** [comment] 2022-10-20 20:35
Thanks! This does indeed take care of saving state properly. Further, I think its a better way of using the TableLayoutPanel than the drag and drop method because the ordering is obvious and "undoing" things can be done by breaking connections. I noticed that dragging a node into the TableLayoutPanel Visualizer could be quite frustrating if it ended up in a position where you didn't want it because there was no easy way to move the pane within the grid that I could find. Maybe the drag and drop functionality should just be gotten rid of since it might need a lot of work to be really useful?

**Comment by glopesdev** [comment] 2022-10-22 22:35
@jonnew The long-term goal is indeed to limit drag-and-drop functionality in favor of the explicit mappings for UI building, but for now our goal was to keep compatibility. I still have to redo internal tests more carefully, but it does look that there are edge cases where the old functionality was lost, so I'll keep this open to evaluate for the patch release.

**Comment by glopesdev** [comment] 2022-11-14 08:48
@jonnew We were discussing this again and reminded ourselves that this was indeed by design to start migrating persistent composite visualizers to using explicitly `VisualizerMapping` nodes.

The idea is for now we will keep the drag-drop functionality as a debugging aid, so you can quickly check something on the fly, but these will not be persisted across runs of the workflow. In the future we might revisit this and either eliminate the drag-drop feature altogether or find a better way to integrate both under the same framework.

Closing as "not planned".

**Closed by glopesdev** 2022-11-14 08:48 UTC
Labels: bug
