### ISSUE TITLE
Issues installing bonsai 2.6.2

### ISSUE THREAD

**Issue by crewl2** [bonsai-rx/bonsai#813] opened 2021-08-23 21:47 UTC
I get the following error when trying to install bonsai 2.6.2

Error downloading 'Rx-Interfaces.2.2.5' from 'https://www.myget.org/F/bonsai/api/v2/package/Rx-Interfaces/2.2.5'

**Comment by glopesdev** [comment] 2021-08-24 15:15
@crewl2 I believe this is a duplicate of #764

**Closed by glopesdev** 2021-08-24 15:15 UTC
Labels: duplicate

**Comment by crewl2** [comment] 2021-08-24 23:17
I tried deleting the bonsai.config and I'm still getting the same error.

**Comment by crewl2** [comment] 2021-08-24 23:24
In addition, now that it's "installed" I get a message to either repair or uninstall the program. I tried repairing and restarting my computer, but I have not been successful.

**Comment by glopesdev** [comment] 2021-08-24 23:40
You probably need to both delete Bonsai.config file and the Packages folder both. If installing Bonsai after that still does not work, you could try uninstalling and deleting the entire Bonsai folder then reinstalling.

This issue is specific to 2.6.2 and is already fixed for the next release.
