### ISSUE TITLE
Consider allowing users to "rename" subjects using the "subject" entry in the toolbox

### ISSUE THREAD

**Issue by bruno-f-cruz** [bonsai-rx/bonsai#762] opened 2021-02-15 13:39 UTC
I think it would be a nice way to change a subject name that would propagate to all the currently assigned subscribers. This would allow users to effortlessly change subject names, making code more readable, without the hassle of having to find every single subscriber/multicast and changing the names accordingly.
Thanks!

**Comment by glopesdev** [comment] 2021-08-07 22:18
Related to #702. Using the toolbox for renaming is a good idea.

**Comment by glopesdev** [comment] 2022-06-04 19:38
Duplicate of #702

**Closed by glopesdev** 2022-06-04 19:38 UTC
Labels: proposal
