### ISSUE TITLE
Issues after updating Bonsai

### ISSUE THREAD

**Issue by benefron** [bonsai-rx/bonsai#1034] opened 2022-09-12 07:59 UTC
### Discussed in https://github.com/bonsai-rx/bonsai/discussions/1033

<div type='discussions-op-text'>

<sup>Originally posted by **benefron** September 12, 2022</sup>
Hello,
I updated all the packages for Bonsai (All sources)
When I am opening Bonsai with one of my projects or even create a new project I get a big red X all over the workflow and a warning message.
I am adding a screen capture and the full text of the warning.
I a updated the packages because of an issue with python transform node that worked before and suddenly was not recognized anymore.
Would appreciate some help ASAP since I can not run my experiments in the current situation  
[Bonsai_crash_120922.txt](https://github.com/bonsai-rx/bonsai/files/9545938/Bonsai_crash_120922.txt)
![1662969413578](https://user-images.githubusercontent.com/29516660/189601954-9276bc59-c0b3-42ce-bc73-6d7bd5d5b7f5.jpg)
</div>

**Comment by glopesdev** [comment] 2022-09-19 07:59
Duplicate of #1042

**Closed** 2022-09-19 08:00 UTC
